### ISSUE TITLE
docs: state that `kustomize` should be installed

### ISSUE THREAD

**Issue by davidxia** [GoogleCloudPlatform/gcs-fuse-csi-driver#12]
State in [docs here](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/docs/installation.md#install) that `kustomize` should be installed. Otherwise, `make` command will fail [at these lines](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/5ac00a8cae55e64ef6c03dad7840e2c443a6e3de/Makefile#L191-L193).

**Comment by songjiaxun** [comment]
Fixed in commit https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/commit/5b8c5ecb4145d274f2eaddf2e38e1801aa2eb06e, thanks!
