### ISSUE TITLE
RBAC improvements

### ISSUE THREAD

**Issue by msau42** [GoogleCloudPlatform/gcs-fuse-csi-driver#17]
https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/b9a071a62e356ee65cb1a311a82959b601054576/deploy/base/controller/controller_setup.yaml#L36

- Are the secrets and service account token permissions required? They are very permissive
- Is the DaemonSet permission required?

**Comment by songjiaxun** [comment]
Please note that in the GKE release, we don't support dynamic provisioning, so controller, and the secrets and service account token permissions are not included in the GKE system.

This setup is only for test purposes.

Moving forward, if we make a definite decision to not invest on the dynamic provisioning, I will clean up all the controller-related code and setup.
