### ISSUE TITLE
Fix documentation for sidecard unlimited resources on Autopilot 

### ISSUE THREAD

**Issue by bhack** [GoogleCloudPlatform/gcs-fuse-csi-driver#170]
Related to: https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/61

Can we fix the documentation to specify that this feature is not available on AutoPIlot?
https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#sidecar-container

This page is labeled both Autopilot and Standard.

**Comment by songjiaxun** [comment]
Updated the doc: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#sidecar-container with two notes:

> Note: Autopilot might overwrite your sidecar container resource configuration. To learn more, see [Resource requests in Autopilot](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests).

> Note: You cannot use value "0" to unset the sidecar container resource limits and requests on Autopilot clusters.

**Comment by bhack** [comment]
it seems it is possible now but I don't know the minimal GKE version.
