### ISSUE TITLE
The sidecar container is at the spec.containers[0] position which may cause issues in some workloads

### ISSUE THREAD

**Issue by songjiaxun** [GoogleCloudPlatform/gcs-fuse-csi-driver#20]
The current sidecar container injection logic will inject the sidecar container at the `spec.containers[0]` position in a Pod.

The design makes sure that kubelet or the container runtime will start up the sidecar container first to obtain the file descriptor of the mount point. Otherwise, the other containers that consume the mount point will hang in the start up step.

This design may break some application's assumption, for example, the [Airflow Kubernetes Executor](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html) assumes that the `base` container is always at the `spec.containers[0]` position in the worker Pod, which conflicts with the sidecar container injection logic.

We are waiting for the KEP for sidecar container pattern: https://github.com/kubernetes/enhancements/pull/3761. After the KEP is accepted and implemented, we will migrate to leverage the native supported sidecar container pattern.

A workaround is to modify the workload Pod to manually inject the sidecar container. Then the sidecar container can be at any position in the container array. However, if the sidecar container is at a later position than the workload container that consumes the volume, the workload container start up will hang 2 minutes and timeout. But the sidecar container start up will proceed. Whenever the sidecar container starts up, the workload container can start as usual.

**Comment by songjiaxun** [comment]
The KEP for sidecar container pattern https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers is implemented and merged: https://github.com/kubernetes/kubernetes/pull/116429

> The new feature gate "SidecarContainers" is now available. This feature introduces sidecar containers, a new type of init container that starts before other containers but remains running for the full duration of the pod's lifecycle and will not block pod termination.

This change can be a good solution.

**Comment by daikeshi** [comment]
Hey @songjiaxun, since https://github.com/kubernetes/kubernetes/pull/116429 is merged, is there any plan to address this issue?

**Comment by songjiaxun** [comment]
Hi @daikeshi , yes, we are targeting early April 2024 to adopt the native sidecar container feature starting with GKE 1.29 clusters.

**Comment by songjiaxun** [comment]
The new GKE version rollout completed. Starting from GKE `1.29.3-gke.1093000`, the CSI driver injects the GCSFuse sidecar container as an init container.

To try out the new feature, please upgrade your GKE cluster to `1.29.3-gke.1093000` or later, and make sure ALL your nodes are also upgraded to GKE version 1.29 or later, then re-deploy your workloads.

Closing this issue for now.
