### ISSUE TITLE
Add monitoring feature

### ISSUE THREAD

**Issue by aliaksei-karneyeu** [GoogleCloudPlatform/gcs-fuse-csi-driver#204]
Hey guys, thanks for all you great work.

Are there any plans to support exporting stackdriver metrics export?

There is [option in gcsfuse app](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/flags.go#L283C13-L283C40) that will enable export metrics via stackdriver.

Thanks in advance.

**Comment by songjiaxun** [comment]
Hi @aliaksei-karneyeu we are working on estimating how to export these metrics on GKE. I will update with more information later. Can you share what gcsfuse metrics you would like to collect?

**Comment by songjiaxun** [comment]
We are working on [this branch](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/pull/310) to expose GCSFuse metrics via CSI.

**Comment by bhack** [comment]
In he mean time is this still valid? https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/docs/monitoring.md

Cause recently I don't fined anymore the metrics in the Metrics Explorer.

**Comment by hime** [comment]
Hi @aliaksei-karneyeu, we now support Cloud Storage FUSE metrics and integration with our managed GKE CSI driver. These metrics are available free of charge through the Metrics Exploer. For details, see our [Metrics Overview](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#gcsfuse-metrics). We are working to add more details on how users can leverage these metrics.
