### ISSUE TITLE
On Autopilot clusters, you cannot upload files larger than 10Gi

### ISSUE THREAD

**Issue by songjiaxun** [GoogleCloudPlatform/gcs-fuse-csi-driver#21]
On GKE Autopilot clusters, according to the doc [Resource requests in Autopilot](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests):

> The ephemeral storage request must be between 10 MiB and 10 GiB for all compute classes and hardware configurations.

> Ephemeral storage: Autopilot modifies your ephemeral storage requests to meet the minimum amount required by each container. The cumulative value of storage requests across all containers cannot be more than the maximum allowed value. Autopilot scales the request down if the value exceeds the maximum.

This means, even you specify a value larger then 10Gi for the annotation `gke-gcsfuse/ephemeral-storage-limit`, GKE Autopilot will scale down the request to make the value under 10Gi.

This also means, on GKE Autopilot cluster, you cannot use the CSI driver to upload files that larger than 10Gi.

We have a few potential solutions:
- A standard PD instead of an ephemeral storage can be used to support the write/upload operations to remove this limitation.
- The underlaying GCSFuse could possibly support write-through that does not require a staging temp storage, which can also remove this limitation.

**Comment by peterSW** [comment]
Thank you for documenting this issue. It has helped me to understand the Pod evictions I have seen in the application I am developing. This application will routinely write files in excess of 100GiB.

Is it currently possible to use the first potential solution (use standard PD instead of an ephemeral storage)?
If not, is there any intention of making that possible?

Are you aware of any issue tracking the possibility of GCSFuse supporting write-through that I could monitor?

**Comment by bhack** [comment]
@songjiaxun Can we add in the meantime some stats in the sidecar log (like the GC log prints) related to the ephemeral-storage size?
As the evictions limits are shared between the sidecard and the pod it is hard to understand when the ephemeral is under pressure by the csi temp storage or by pod for unrelated ephemeral folders.

**Comment by bhack** [comment]
> The ephemeral storage limit on the sidecar container will be used for the entire Pod, which will also affect other workload containers. This is a known issue, or more precisely, an expected behavior. We documented this on the [GKE documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#prepare-mount). @bhack Let me do some research to see if it's feasible to add some log in the sidecar container.

Yes the specific case about the log is when you can still solve your workload with the current ephemeral limits but you don't really know how much to request. 
Often you need to debug if you have still something writing to the ephemeral storage on your pod that you don't want and  that it wasn't related to the CSI gcsfuse volume write folders or instead it is really the gcfuse  'tmp` to put pressure on the ephemeral.
So It will be really useful info to have specially as the write-through has a lower priority.

**Comment by songjiaxun** [comment]
We now support the custom buffer volumes, see details in the doc: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#buffer-volume

Note that you need to upgrade your clusters to the required versions to use this feature: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#requirements

Closing this issue. Let's use https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/34 to track the resource profiling/logging issue.
