### ISSUE TITLE
For a non default gcloud config the project selection is buggy

### ISSUE THREAD

**Issue by saikat-royc** [GoogleCloudPlatform/gcs-fuse-csi-driver#247]
For a gcloud config list like:
```
[compute]
region = us-central1
zone = us-central1-c
[core]
account = <email>
disable_usage_reporting = True
project = <gcp project>

Your active configuration is: [test-dev-config]
```

the script used in the Makefile 
`PROJECT ?= $(shell gcloud config get-value project 2>&1 | head -n 1)`
outputs string "Your active configuration is: [test-dev-config]"

This misconfigures the csidriver object spec "audience" field, and hard to debug.

$ gcloud config get-value project 2>&1
Your active configuration is: [test-dev-config]
<my gcp project>

This misconfigures the csidriver audience, and hard to debug. I think its better to make the PROJECT a mandatory field, instead of auto detect for a consistent behavior

**Comment by songjiaxun** [comment]
This commit improves the Makefile: https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/commit/1384aabd0f08eb4d4875e5be012a03f89cc5f0e3

Instead of using `gcloud`, this change uses `kubectl` to fetch the cluster project information, which is always the correct project.
