### ISSUE TITLE
insufficient ephemeral storage in static mountning mode

### ISSUE THREAD

**Issue by lewanbla** [GoogleCloudPlatform/gcs-fuse-csi-driver#28]
While mounting buckets in a static way one has to be aware of ephemeral storage default value.

Case: GKE Node with 2G RAM. Mounting in static mode (PV/PVC) 10Gi. Annotations: gke-gcsfuse/volumes: "true"
With the above setup it will not work - error with insufficient ephemeral storage appears because the **default ephermeral value is 5Gi** which is greater than k8s **ephemeral volume limit which is 1/2 of node RAM**.

Workaround: add annotations: gke-gcsfuse/ephemeral-storage-limit: 100Mi (or other arbitrary value less than 1/2 of node RAM)

**Comment by songjiaxun** [comment]
Could you point me to the documentation describing "k8s ephemeral volume limit which is 1/2 of node RAM"? Is this a GKE requirement? Thank you!

**Comment by songjiaxun** [comment]
@lewanbla are you still having the issue? Could you share the documentation mentioning "k8s ephemeral volume limit which is 1/2 of node RAM"?

**Comment by songjiaxun** [comment]
Closing this issue for now, but feel free to re-open with more information.
