### ISSUE TITLE
How does this work without a secret?

### ISSUE THREAD

**Issue by vsoch** [GoogleCloudPlatform/gcs-fuse-csi-driver#3]
Hi again! I'm close to testing this out, and I thought it was curious that no secret is defined. When I tested it out, indeed my operator logs told me that one is required:

```console
1.676949727749151e+09   ERROR   Reconciler error        {"controller": "minicluster", "controllerGroup": "flux-framework.org", "controllerKind": "MiniCluster", "miniCluster": {"name":"flux-sample","namespace":"flux-operator"}, "namespace": "flux-operator", "name": "flux-sample", "reconcileID": "32f2f18f-4468-4a62-a8c3-a95f89a8db55", "error": "PersistentVolume \"data\" is invalid: [spec.csi.controllerPublishSecretRef.name: Required value, spec.csi.nodePublishSecretRef .name: Required value]"}
```

I don't see any mention of a secret in the docs - is there another way to go about it? I see that there are a few:

```
$ kubectl get secrets --all-namespaces | grep csi
gcs-fuse-csi-driver   default-token-mqzvz                              kubernetes.io/service-account-token   3      57m
gcs-fuse-csi-driver   gcs-fuse-csi-driver-webhook-secret               Opaque                                2      57m
gcs-fuse-csi-driver   gcs-fuse-csi-node-sa-token-2r6r9                 kubernetes.io/service-account-token   3      57m
kube-system           pdcsi-node-sa-token-nmn5k                        kubernetes.io/service-account-token   3      82m
```
Another question I have is (ballpark) how many pods should I leave for the storage to work? Thanks!

**Comment by songjiaxun** [comment]
Hi, thanks for the question.

The CSI driver does not use any secrets. Instead, it relies on the GKE Workload Identity feature, please see the [steps](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/docs/usage.md#set-up-access-to-gcs-buckets-via-gke-workload-identity) to learn about how to configure it.

Because it relies on the GKE Workload Identity feature, currently the driver does not work on other cloud platform.

**Comment by vsoch** [comment]
Thansk @songjiaxun ! So that is exactly the tutorial I was following. The reason I ask about a secret is that when I'm creating the PVC / PV in Go, I get an error if the secret field is empty. In other words, I'm not able to reproduce the example you provide from Go because it doesn't let me make the spec without the secret.

**Comment by songjiaxun** [comment]
Hi @vsoch, sorry for the late reply, as we are focusing on the GKE integration work. Could you explain more about how you are creating PVC/PV in Go? In the current design, the driver does not officially support dynamic provisioning, and all the authentication should use GKE workload identity, so there should not be any secrets involved.

**Comment by songjiaxun** [comment]
Closing this issue for now as no detailed information is provided.

Feel free to reopen it if you are still experiencing the same issue.
