### ISSUE TITLE
Comparison with CSI GCS - sidecar overhead

### ISSUE THREAD

**Issue by Mokto** [GoogleCloudPlatform/gcs-fuse-csi-driver#30]
Hi,

What would you say are the biggest difference between GCS FUSE & https://github.com/ofek/csi-gcs?

Even though I really appreciate the fact this project is officially supported by Google Cloud, I'm a bit concerned about the overhead with FUSE (one sidecar container with 256Mi memory & 5Gi ephemeral storage).

Any take on that?

Thanks.

**Comment by songjiaxun** [comment]
Hi @Mokto , thanks for the question.

The biggest difference between this project and https://github.com/ofek/csi-gcs is that, this project uses the sidecar container to run gcsfuse binary, while the ofek implementation runs gcsfuse instances inside the CSI driver container.

The sidecar container mode give us the following benefits:

- The CSI driver can be updated without the gcsfuse instance interruptions.
- The gcsfuse can leverage the GKE Workload Identity, meaning you don't need to deal with the GCP keys.
- You have flexibility to tune how much resources you want to allocate to the sidecar container using the Pod annotations.

I believe the last point kinda answers your question -- we do set a default resource to the sidecar container, but you have the options to tune how much resources you want to allocate. Please note that, even in the ofek implementation, the FUSE overhead cannot be avoided, it's just a part of the CSI driver container resource. However, this project gives you the ability to explicitly specify the FUSE overhead.

**Comment by songjiaxun** [comment]
Closing this issue as there is no new comments. Feel free to re-open it if you have any questions.
