### ISSUE TITLE
GCS Fuse CSI Driver not auto loading to CronJob  in GKE

### ISSUE THREAD

**Issue by raviprakash007** [GoogleCloudPlatform/gcs-fuse-csi-driver#317]
I am trying to use 
`gke-gcsfuse/volumes: "true" ` in CronJob, but there is no provision as well as documentation available to use the csi driver.  The only documentation is https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#consume-ephemeral-volume-job which doesnot look feasible for CronJob.

What can we do for loading csi fuse driver with Cron Job?

**Comment by raviprakash007** [comment]
# cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: my-namespace
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
         annotations:
            gke-gcsfuse/volumes: "true"
        spec:
          initContainers:
          - name: gcs-sidecar
            image: gke.gcr.io/gcs-fuse-csi-driver-sidecar-mounter:v1.4.1-gke.0@sha256:26aaa3ec5955506ce36c4d9c0bae909401168b9a0f52d36661f66ca0789bea0e
            volumeMounts:
            - mountPath: /cron-jobs
              name: cron-scripts
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello, World!"
            volumeMounts:
            - mountPath: /cron-jobs
              name: cron-scripts
          restartPolicy: OnFailure
          serviceAccount: k8-prod-service-account
          volumes:
          - name: cron-scripts
            persistentVolumeClaim:
              claimName: cronjob-gcs-data-claim

**Comment by raviprakash007** [comment]
It was my mistake, I have solved this by appending a Job template in CronJon Schema.

Here is an example;
`apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: my-namespace
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            gke-gcsfuse/volumes: "true"
        spec:
          serviceAccount: my-k8-service-account
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo "Hello, World!"
              volumeMounts:
                - mountPath: /cron-jobs
                  name: cron-scripts
          restartPolicy: OnFailure
          volumes:
          - name: cron-scripts
            persistentVolumeClaim:
              claimName: cronjob-gcs-data-claim
`

**Comment by hime** [comment]
Thanks for clarifying! Closing this issue as it's now resolved. Feel free to reopen if you run into any related issues with CronJob and setting required GCSFuse CSI annotations.
