### ISSUE TITLE
wrong architecture in v1.5.0 image 

### ISSUE THREAD

**Issue by nikolaydubina** [GoogleCloudPlatform/gcs-fuse-csi-driver#356]
- GKE cluster is running on `linux/amd64`
- other images are `linux/amd64` (e.g. [v1.4.3](https://gcr.io/gke-release/gcs-fuse-csi-driver-sidecar-mounter@sha256:a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f))

however, [v1.5.0](https://gcr.io/gke-release/gcs-fuse-csi-driver-sidecar-mounter@sha256:a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f) image is build for `linux/arm64`. which can be verified in Docker

<img width="642" alt="image" src="https://github.com/user-attachments/assets/e6ad8af6-4426-483f-a2ea-930ecf2bfd50">

this causes problems on startup of container, with error like this

<img width="707" alt="image" src="https://github.com/user-attachments/assets/af429f21-08d8-4524-b5ef-630d89bc53ee">

please fix. thx.

**Comment by hime** [comment]
Hi @nikolaydubina, could you provide more details for replicating this issue? Could you share more details about your setup and workload deployment? 

Some more helpful information would be:
- Are you using Non-managed driver?
- Are you using a privately hosted sidecar image?

**Comment by nikolaydubina** [comment]
> Are you using non-managed driver?

I am following https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#private-image

I am running in private nodes, and have to use private image.

I guess this is "non-managed" driver.

> Are you using a privately hosted sidecar image?

yes

**Comment by hime** [comment]
Thanks! Could you confirm the image you're using and how you got it? Do you have the image SHA that's placed in your workload yaml? The links in the description point to the same place.

**Comment by nikolaydubina** [comment]
I get image from here:

https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#private-image > https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/docs/releases.md#gke-compatibility

then the one at the bottom for v1.5.0

https://gcr.io/gke-release/gcs-fuse-csi-driver-sidecar-mounter@sha256:a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f

<img width="914" alt="image" src="https://github.com/user-attachments/assets/64425e2b-3abb-44fe-95f5-ffa93b78a3d3">

image

https://console.cloud.google.com/artifacts/docker/gke-release/us/gcr.io/gcs-fuse-csi-driver-sidecar-mounter/sha256:a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f

gcr.io/gke-release/gcs-fuse-csi-driver-sidecar-mounter@sha256:a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f

**Comment by hime** [comment]
That's odd. I'll try to recreate this week...

I'm curious if there's an external factor at play, could you share the cluster ID with me? You can get the ID by running gcloud container `clusters describe <cluster-name> --location <cluster-location> | grep id:`, and share the id with me? Thanks!

**Comment by nikolaydubina** [comment]
hey, sorry will have to back off here. can't share cluster id (other ids from my GCP) for security reasons.

I can share details of my cluster / nodes tho. hope that helps:

```
1.30.5-gke.1014001
asia-southeast
IPv4
Cloud Storage Fuse CSI driver: Enabled
Container-Optimized OS with containerd (cos_containerd)
```

as for sidecar spec, I am closely following: https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/docs/sidecar-manual-injection.md

as for the rest, I think this should be possible to repro in brand new cluster.

**Comment by hime** [comment]
Could you share the exact steps you are doing to:
1. Copy the image from public artifact registry to your machine
2. Steps if you're doing anything to the image locally.
3. Push image to your private registry

Our original image manifests have not changed. For example, the [v1.5](https://pantheon.corp.google.com/artifacts/docker/gke-release/us/gcr.io/gcs-fuse-csi-driver-sidecar-mounter/sha256:a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f;tab=manifest?e=-13802955&inv=1&invt=AbfvPQ&mods=logs_tg_prod) image manifest still handles both arm and amd.

**Comment by nikolaydubina** [comment]
```bash
docker pull --platform=linux/amd64 gcr.io/gke-release/gcs-fuse-csi-driver-sidecar-mounter@sha256:a527a083127fb456c96a6e4a478639222065dc0c2d485729e63605035d624f8f
```

now produces amd64

<img width="1130" alt="image" src="https://github.com/user-attachments/assets/699336fe-b1ef-47d5-95ac-5edb14e949fa">

maybe I did not use `--platform` flag before? but I used same command to pull all images last time, how come other images were pulled correctly and this was not? anyways, odd!

**Comment by hime** [comment]
`ARG TARGETPLATFORM` can be set externally and can affect the selection of which gcsfuse binary architecture is selected. I'm not entirely sure how this can happen when pulling the image locally or pushing it to private registry. 

I'm not familiar with the interface that you're using to view the image architecture. Could you share what that is? If you could share the steps you took to get there would be helpful too (to document it)!!

**Comment by nikolaydubina** [comment]
right. this is layers for image as seen in Docker desktop

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/3d29122b-4255-48cd-9e70-5d0daccabdb4">

**Comment by nikolaydubina** [comment]
thanks for investigating this @hime. 

probably good idea to have test that hits image registry for all platforms you expect. 🤔

**Comment by hime** [comment]
Created item to track documentation guide improvements. Closing as issue is now resolved.
