### ISSUE TITLE
Sidecar crash

### ISSUE THREAD

**Issue by bhack** [GoogleCloudPlatform/gcs-fuse-csi-driver#36]
Recently the sidecar started to constantly crash after few minutes the pod started with this repeating error:

```
E0609 LookUpInode: interrupted system call, list objects: Error in iterating through objects: context canceled
E0609 fuse: *fuseops.LookUpInodeOp error: interrupted system call
E0609 LookUpInode: interrupted system call, list objects: Error in iterating through objects: context canceled
E0609  fuse: *fuseops.LookUpInodeOp error: interrupted system call
E0609  ReadFile: interrupted system call, fh.reader.ReadAt: readFull: context canceled
E0609  *fuseops.ReadFileOp error: interrupted system call
```

Dirver version
`Running Google Cloud Storage FUSE CSI driver sidecar mounter version v0.1.3-gke.0`

GKE
`1.26.3-gke.1000`

**Comment by bhack** [comment]
Just an update on this, 
I found was a small problem in the POD so I think we need to just give a better message in the sidecar when the problem is from the POD instead of sending all these messages.

Otherwise you have to check "to the millimeter" with all timestamps between the pod and the sidecar

**Comment by songjiaxun** [comment]
The gcsfuse error `E0609  ReadFile: interrupted system call, fh.reader.ReadAt: readFull: context canceled` indicates that the read operation was cancelled by the user's application. The gcsfuse did not crash in this case.

As for the resource limit on Autopilot clusters, let's use https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/35 to track the limitation.

Closing this issue for now as there is no action needed. Feel free to re-open if detailed logs shows that the timestamps between the pod and the sidecar being messed up.
