### ISSUE TITLE
Synchronization Issue between gcsfuse and Kubernetes Pod: 'No Such File or Directory' Error on File Update

### ISSUE THREAD

**Issue by leylmordor** [GoogleCloudPlatform/gcs-fuse-csi-driver#44]
I am encountering a synchronization issue between gcsfuse and a pod in Kubernetes environment. When I update the files in the Google Cloud Storage (GCS) bucket mounted by gcsfuse, the gcs fuse sidecar fails to access the updated files and throws an error.

Error Logs:
```
fuse: *fuseops.ReadFileOp error: no such file or directory
ReadFile: no such file or directory, fh.reader.ReadAt: startRead: NewReader: storage: object doesn't exist
```

Configuration:

GKE Pod: Mounted GCS bucket using gcsfuse with the following configuration:
mountOptions: 'uid=101,gid=82'

Kubernetes Job: Updates the contents of the GCS bucket by replacing the existing files. Names are not changed.

Observations and Troubleshooting Steps Taken:

- Verified that the files are successfully uploaded to the GCS bucket by the Kubernetes Job.
- Confirmed that the gcsfuse volume is correctly mounted in the pod.
- Ensured consistent file naming between the updated files and the files accessed by the GKE Pod.
- Verified file system permissions and confirmed that the uid and gid specified in the mountOptions match the permissions required by the Pod.
- Tried setting stat-cache-ttl=0, type-cache-ttl=0, implicit-dirs in the mount options

Anything that I'm missing here?

**Comment by songjiaxun** [comment]
Could you clarify the workflow a little bit?

1. Before you mount the bucket, does the file exist in the bucket?
2. Was the file initially created by gcsfuse?
3. Is the file in a subfolder or in the root path of the bucket? If in a subfolder, was the subfolder created by gcsfuse?
4. How large is the file?
5. Did your Job try to access the updated file immediately after it's updated?

I am trying to collect enough information to reproduce the issue on my end. Thank you!

**Comment by leylmordor** [comment]
@songjiaxun 
1. Yes
2. No
3. In the root folder, files were already in the bucket
4. 70MB
5. Yes.

So first we download the files using shell script to the bucket which is mounted to a path and then we try to access the files after the download is complete.

**Comment by songjiaxun** [comment]
Hi @sethiay , could you help take a look at this issue?

Seems like disabling cache and enabling implicit dir using `stat-cache-ttl=0, type-cache-ttl=0, implicit-dirs` does not help in this case.

**Comment by skyjacker2005** [comment]
Any solution to this issue ? We have the same situation.
In our case access to GCSFuse mounted volume works well if we have only one pod replica.
In case of 2 replicas unfortunately it seems that the second replica is not able to immediately see what is updated from the first.

**Comment by songjiaxun** [comment]
Hi @raj-prince , seems like in @skyjacker2005 case, two gcsfuse instances cannot sync the file states immediately. Can you provide some suggestions here? Is this expected?

**Comment by skyjacker2005** [comment]
Hi @raj-prince,

we don't manage how exactly the code access to filesystem files.
We simply use the standard unpickler load method of the "pickle" library for python object serialization.
https://github.com/python/cpython/blob/3.12/Lib/pickle.py (line 1179)

It's very strange that GCSFuse doesn't work as expected with a standard library that is used with success with other ReadyWriteMany file systems (ourselves are using the library with NFS versions 3 and 4 and the CephFS competitor). 

Thanks a lot

**Comment by raj-prince** [comment]
@skyjacker2005 Could you please confirm are you using the same fileHandle to create the [Unpicker](https://github.com/python/cpython/blob/3.12/Lib/pickle.py#L1131) object or not?

In the meantime, I'll discuss within team regarding this behavior and come back to you.

**Comment by skyjacker2005** [comment]
@raj-prince we use it to pick sessions we store in filesystem (to be available to all replicas).

In our code I see:

f = open(self.get_session_filename(sid), "rb")

Then "f" is passed to a function executing:
unpickler = Unpickler(stream, encoding=encoding)
return unpickler.load()

Where the default encoding is ASCII.

unpickler.load fails with errors logged both from our code and gcsfuse (FileNotFoundError)

Thanks again

**Comment by raj-prince** [comment]
Thanks for the information!

Ohh, that means the same "f" is passed to the function executing `Unpickler(stream, encoding=encoding)`.
If yes, Is it possible to pass different fileHandle to the function executing `Unpicker` logic?

**Comment by skyjacker2005** [comment]
I don't undestand why do you think the same file handle is passed to the function Unpickler(stream, encoding=encoding) ?
"f" is a local variable created on the fly. Everytime a new one is used.

**Comment by raj-prince** [comment]
Got it. This is strange.

There are two options now:
(a) Either to reproduce the same issue our side - this might take some time. Although if you could provide small reproducer for the issue that will be very helpful.
(b) You can provide bucket_name, cluster_id via creating an internal customer [support ticket](https://support.cloud.google.com/portal/), we can check GCS logs, that will be quicker.

Thanks,
Prince Kumar.

**Comment by raj-prince** [comment]
@skyjacker2005 , could you please open a [support-ticket](https://support.cloud.google.com/portal/) as we need bucket-name, project-number, cluster-id to access GCS, gcsfuse logs? Otherwise, it's hard to debug.

**Comment by skyjacker2005** [comment]
@raj-prince as soon as possibile we'll do it. Unfortunately I'm not the person in charge of the cloud project administration therefore I'm internally forwarding the question. 

Thanks again,
I'll update you asap.

**Comment by ashmeenkaur** [comment]
Just to reiterate what was mentioned in  https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/44#issuecomment-2070847349:

Mounting gcsfuse with `--stat-cache-ttl 0` && `--type-cache-ttl 0` should reduce the occurrence of this issue. The tradeoff is an increase in GCS stat/list calls (more details [here](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#caching)).

In addition to what was discussed in https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/44#issuecomment-2070847349, this issue can also arise when there are concurrent reads and writes to GCS from different GCSFuse mount points.

Example Scenario:
Let's say there are two mounts:
- `gcs1` (for reading `sync_test.txt`)
- `gcs2` (for writing `sync_test.txt`) 

`sync_test.txt` is a file on the bucket. (This issue is easier to reproduce with a large file. I used a 4GB file – but it can happen with small files as well.)

Scenario:
```
(a) Created a fileHandle in gcs1: fd = os.open("gcs1/sync_test.txt", os.O_RDWR|os.O_DIRECT)
(b) Read via fd: os.read(fd, 1)
(c) While (b) is in progress, update the sync_test.txt via gcs2
(d) The in-progress read on gcs1 will fail with the error: `No such file or directory`
```
**Note:** Reading via a new file handle would work successfully only if it file handle is opened after the file has been updated/written by the other mount.

**Next Steps:**
For further debugging, the customer will open a support ticket and share the bucket name, project number, and cluster ID.

Please feel free to reopen this issue if you have any other questions.

Thanks,
Ashmeen
