### ISSUE TITLE
The sidecar container violates Restricted Pod Security Standard

### ISSUE THREAD

**Issue by songjiaxun** [GoogleCloudPlatform/gcs-fuse-csi-driver#52]
# Symptom

When the [Restricted Pod Security Standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) is enforced, the Pod will throw error:

```
pods "xxx" is forbidden: violates PodSecurity
...
"gke-gcsfuse-sidecar" must set securityContext.capabilities.drop=["ALL"])
```

# Root Cause

The sidecar container has the drop as "all", instead of "ALL".

# Workaround

Similar to https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/20#issuecomment-1584905857, you can manually inject the sidecar container using drop "ALL".

# Fix

This is fixed by https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/commit/6a0bdba8e7cc69f1fde3cbccf4ca726f6994a83e and will be included in the next release.

**Comment by siarhei-cma** [comment]
When will the rollout of the v 0.1.5 to GKE be completed? As of now - end of the day Oct 20, our pods still run v 0.1.4. 

Could you please also let me know how to trigger the update? I tried redeploying the pods and removing, re-adding "gke-gcsfuse/volumes" annotation.

This is a time sensitive issue since we need to migrate to Kubernetes 1.25 before Oct 31 and our security team requires us to apply the restricted standard. The statement "not thoroughly tested" in the workaround is not reassuring. 
Thank you!

**Comment by songjiaxun** [comment]
Hi @siarhei-cma , we recently experienced some difficulties on the new version roll out. Sorry about that!

Now the new CSI driver version `0.1.6` has already rolled out. Please upgrade your cluster to `1.25.14-gke.1474000` to use the new CSI deriver. This issue is resolved in that version.

Please kindly let me know if this GKE cluster version unblocks your workload. Thank you!

**Comment by siarhei-cma** [comment]
Thank you @songjiaxun! We actually running "stable release channel". The versions are not updated as frequently. Our test cluster has 1.25.10-gke.2700. If I stay on the stable channel offered updates are:
- 1.26.7-gke.500
- 1.26.5-gke.2700
- 1.25.12-gke.500

Will any of them have the updated CSI driver?

If I try switching to the Rapid channel, the only option available is 1.26.9-gke.143700. There is a message "You can’t choose release channel version when subscribing to release channels in an existing cluster in the same request." I guess, if switching to the rapid channel is required, it could be two step process: switch to the rapid channel then change the version. I would probably need to stay with Kubernetes 1.26 or higher.

Our production cluster is running 1.24.14-gke.2700. For the stable channel I have upgrade to 1.25.10-gke.2700 and 1.25.12-gke.500 available. If I switch it to the rapid channel the available version is 1.25.14-gke.142100.

I would appreciate it if you suggest how I should proceed. I would like to test the upgrade before applying the change to the production.
Thank you very much!

**Comment by songjiaxun** [comment]
Hi @siarhei-cma , sorry for the confusion.

GKE has changed the release and upgrade model, and currently the new CSI version is only available in the Rapid channel. It will take about 3 weeks for the new version to be available in Regular channel, and about 6 weeks in Stable channel.

So, yes, you will need to switch to the Rapid channel first, then upgrade your cluster to one the following cluster versions to get the new CSI version:

- 1.24.17-gke.2155000
- 1.25.14-gke.1474000
- 1.26.9-gke.1507000
- 1.27.6-gke.1506000
- 1.28.2-gke.1157000


The above cluster versions should be available in the Rapid channel. If you don't see these version, please try upgrading your `gcloud` to the latest version, and run the following command to check if the versions are in the list:

```
gcloud container get-server-config --format "yaml(channels)"
```

**Comment by songjiaxun** [comment]
The new CSI driver release is announced on [GKE release note](https://cloud.google.com/kubernetes-engine/docs/release-notes#October_23_2023).

**Comment by siarhei-cma** [comment]
Thank you very much, @songjiaxun.
