### ISSUE TITLE
What is exact difference between "Provision your volume as a CSI ephemeral volume" vs "Provision your volume using static provisioning" in context of GCSFuse csi

### ISSUE THREAD

**Issue by ashish01987** [GoogleCloudPlatform/gcs-fuse-csi-driver#59]
In general Ephemeral volumes are tied to pods lifecycle. While Static volumes are not  .
That is incase of static volumes data will stay even if pod gets deleted. While for Ephermeral data is lost when pod is deleted.

In case of gcsfuse csi, I see that in both cases (Static as well as ephermeral) data is going to stay on bucket, when pod is deleted.
So I am trying to understand what is the difference between Ephermeral and static volume approach in case of gcsfuse csi.
I have referred to this doc https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver
but could clearly distinguish between two.

The clear distinction will help me to choose between one of the two approaches.

Is it that any of the two approach can be used as per the convenience or there are some cases where one approach is preferred (or will not work)  over other ?

**Comment by songjiaxun** [comment]
@ashish01987 thanks for the question.

You are right about the ephemeral volume in GCS FUSE CSI driver -- the data is going to stay, which makes the volume not totally ephemeral.

The intention to support the ephemeral volume in the CSI driver, like you mentioned, is to make the volume tide to pod lifecycle. This is commonly used in data processing and AI/ML training applications where developers do not need / want to maintain separate PV/PVC objects in the cluster.

On the other hand, some of the applications may only support PV/PVC, so the CSI driver also supports the traditional static provisioning.

As for which way is preferred, it depends on use cases:

- If your application already uses PV/PVC, and you don't want to change the spec too much, then you can just modify your exiting PV to use the CSI driver.
- If there are authentication restrictions in your system, and you don't want your developers to directly interact with the bucket, then cluster admin may want to create PV/PVC for developers.
- If it does not make a lot of sense to create new PV/PVC objects for your applications, then the ephemeral volume may be a better choice.

No matter which interface you chose to use, the underlaying functionality is exactly the same. And in most of use cases, these two interfaces should be exchangeable.
