### ISSUE TITLE
Instructions with tag no longer work

### ISSUE THREAD

**Issue by vsoch** [GoogleCloudPlatform/gcs-fuse-csi-driver#7]
I'm trying to reproduce what I did a few weeks (months?) ago, and I'm a bit confused because previously there was a version 0.4.x and now it looks like it's reverted back to  0.1.x. I tried the same strategy as before, but it still used a git "dirty" tag that doesn't exist, so I believe something has changed in the repository since then. 

Would it be possible to provide this example and deployment either with an exact example of an existing image, or not relying on git? The current setup seems very error prone, and this is the second time I'm trying and hitting a bug because of this. For reference, here is my previous issue https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/1 and you can see the tag was a higher version. These instructions that we fixed no longer work.

Thank you and happy Friday!

**Comment by KonradSchieban** [comment]
I have had similar issues with the installation as well. Simply running `make install` did not push the gcs-fuse-csi-driver container images to my registry. Passing the parameter `STAGINGVERSION` with the latest version worked for me to set up the driver: `make install STAGINGVERSION=v0.1.2-0-gd9e3bdd`

**Comment by songjiaxun** [comment]
Thanks for reporting this installation issue.

With a recent [doc fix](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/commit/98cb3c397ee9aa0feea3aa40a6fa87cfa3219d17), you can now specify the STAGINGVERSION and project id when you install the driver, for example:

```
make install STAGINGVERSION=v0.1.2 PROJECT=<cluster-project-id>
```

Closing this issue.
