### ISSUE TITLE
the webhook failed to inject the sidecar container into the Pod spec!!!

### ISSUE THREAD

**Issue by Zy1bREAd** [GoogleCloudPlatform/gcs-fuse-csi-driver#89]
在给pod单独添加注释后会接着抛出该错误了，但没能找到相对应的解决办法

**Comment by Zy1bREAd** [comment]
<img width="1395" alt="image" src="https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/assets/93694041/f82387d2-3372-4e47-b122-6bb608cf7688">

**Comment by Zy1bREAd** [comment]
After adding a separate comment to the pod, the error will be thrown, but the corresponding solution cannot be found.
Do I need to find certain logs to analyze? 
My purpose is to mount the bucket as a PV on the corresponding statefulset.
Thanks!!!

**Comment by Zy1bREAd** [comment]
<img width="1397" alt="image" src="https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/assets/93694041/6ff3ae62-986c-4ed4-a3ee-e9e2d8ec5139">

**Comment by songjiaxun** [comment]
Hi @Zy1bREAd , could you share the StatefulSet and PV/PVC spec? I'd like to understand the "separate comment" you added. Also, are you using the GKE managed CSI driver, or did you manually install the driver?

**Comment by Zy1bREAd** [comment]
@songjiaxun This is my sts
<img width="1020" alt="image" src="https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/assets/93694041/90a2c8d5-5510-4721-b1c0-8113e134f684">

**Comment by Zy1bREAd** [comment]
<img width="1398" alt="image" src="https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/assets/93694041/8f767a0d-c099-4aec-a7df-4c9fb29f96e0">

**Comment by songjiaxun** [comment]
@Zy1bREAd 看起来你的CSI driver是GKE管理的，但是我还是没有看到你说的“在给pod单独添加注释”。请问可以分享你单独添加的注释么？谢谢！

**Comment by Zy1bREAd** [comment]
@songjiaxun Thanks!!!This is the comment I added individually to the pod. Currently, I refer to your article https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/20 (should it be the way to mount CSI temporary volumes?) and have successfully mounted the volume, but How do I modify this permission? I used chmod and chown but it didn't work!
<img width="504" alt="image" src="https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/assets/93694041/12e14ebd-4b40-4a67-80e1-93321a78d2e2">

Permissions will not change, causing my es write data access to be denied
<img width="506" alt="image" src="https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/assets/93694041/e2d4b92c-d881-4c20-9bc7-9b29882dbdca">

**Comment by songjiaxun** [comment]
Hi @Zy1bREAd , the page you followed in https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/20#issuecomment-1584905857 is just a workaround. In your case, I don't think you want to manually inject the sidecar container. Or if you need to, please remove the annotation *gke-gcsfuse/volumes:"true"* from your Pod spec, because it will conflict with the webhook injection logic.

As for the permission issue, yes, chmod does not work with the GCSFuse. Please set `uid` and `gid` in `mountOptions`. See the [GKE doc](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#mounting-flags) for details.

**Comment by Zy1bREAd** [comment]
Hi,@songjiaxun  Thank answer!!! However, I read in the documentation that FUSE cannot be used without adding this annotation. In fact, I added annotations to statefulset, but my pods never had them, and they were all added manually.

`        - name: gcs-fuse-csi-ephemeral
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: hasepoc-pv
              mountOptions: "uid 1001 --gid 1001"`
Regarding the permission issue, I used the following mount flags but couldn't mount it. I think there is something wrong with my syntax. Can you give me some suggestions? Thanks

**Comment by songjiaxun** [comment]
Hi @Zy1bREAd , sorry for the delay.

The annotations should be added to `spec.template.metadata.annotations`. See https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#pod-annotations

The mountOptions should be "uid=1001,gid=1001".

**Comment by songjiaxun** [comment]
Closing this case for now. @Zy1bREAd feel free to re-open it if you have other questions.
