### ISSUE TITLE
CSI Driver tokenRequests value incorrect when setting up from Cloud Shell

### ISSUE THREAD

**Issue by KonradSchieban** [GoogleCloudPlatform/gcs-fuse-csi-driver#9]
When you set up the CSI Driver from Cloud Shell the CSI Driver picks up a wrong value in the `TOKENREQUESTS` audience field. As a result, pods will not be able to mount any storage volumes and show the error message in the logs:

Pod event warning: MountVolume.SetUp failed for volume "xxx" : rpc error: code = Internal desc = failed to prepare storage service: rpc error: code = Internal desc = storage service manager failed to setup service: timed out waiting for the condition.

Workaround:

1. Manually delete the csidriver using `kubectl delete csidriver gcsfuse.csi.storage.gke.io`
2. Update the file `deploy/base/setup/csi_driver.yaml` and edit the property value `audience` <img width="397" alt="image" src="https://user-images.githubusercontent.com/6935519/231290415-8d1e71da-451c-4682-9cc2-df2965e97f33.png">
3. Recreate the csidriver using `kubectl apply -f deploy/base/setup/csi_driver.yaml`
4. In case there are running deployments, clean up the environment and redeploy.

**Comment by songjiaxun** [comment]
Thanks for reporting this installation issue.

With this [fix](https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/commit/98cb3c397ee9aa0feea3aa40a6fa87cfa3219d17), you can now specify the project id when you install the driver, for exampe:

```
make install STAGINGVERSION=v0.1.2 PROJECT=<cluster-project-id>
``` 

Closing this issue.
